=== minhngo248/minhngo248.github.io/src/data/personal.dtd
<!ELEMENT personal (info, education, projects)>

<!ELEMENT info (img)>

<!ELEMENT img (#PCDATA)>

<!ATTLIST img
    src CDATA #REQUIRED
>

<!ELEMENT education (3if, 4if)>
<!ELEMENT 3if (sem1, sem2)>
<!ELEMENT 4if (sem1, sem2)>
<!ELEMENT sem1 (module+)>
<!ELEMENT sem2 (module+)>
<!ELEMENT module (subject+)>
<!ATTLIST module
    name CDATA #REQUIRED
>
<!ELEMENT subject (#PCDATA)>
<!ATTLIST subject
    src CDATA #REQUIRED
>

<!ELEMENT projects (time+)>
<!ELEMENT time (project+)>
<!ATTLIST time 
    time CDATA #REQUIRED>
<!ELEMENT project (#PCDATA)>
<!ATTLIST project
    src CDATA #REQUIRED>

=== minhngo248/minhngo248.github.io/src/data/personal.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="personal.xsl"?>

<!DOCTYPE personal SYSTEM "personal.dtd">
<personal>
    <info>
        <img src="img/Ngoc_Minh.jpg"/>
    </info>

    <education>
        <if3>
        <sem1>
        <module name="Architecture, System and Network">
            <subject src="/subjects/3if/first_sem/IF-3-AC.pdf">Digital Circuits</subject>
            <subject src="/subjects/3if/first_sem/IF-3-AO.pdf">Computer Architecture</subject>
            <subject src="/subjects/3if/first_sem/IF-3-PRC.pdf">C language programming</subject>
        </module>
        <module name="Software Development">
            <subject src="/subjects/3if/first_sem/IF-3-ALGO.pdf">Algorithms and Data Structures</subject>
            <subject src="/subjects/3if/first_sem/IF-3-POO1.pdf">Object Oriented Programming - C++ - Basis</subject>
            <subject src="/subjects/3if/first_sem/IF-3-POO2.pdf">Object Oriented Programming - C++ - Advance</subject>
            <subject src="/subjects/3if/first_sem/IF-3-OP.pdf">Programming Tools</subject>
        </module>
        <module name="Models and Mathematical Tools">
            <subject src="/subjects/3if/first_sem/IF-3-CMSI.pdf">Linear algebra and image synthesis</subject>
            <subject src="/subjects/3if/first_sem/IF-3-TSI.pdf">Signal Processing</subject>
        </module>
        <module name="Information Systems">
            <subject src="/subjects/3if/first_sem/IF-3-MD.pdf">Data Modelling</subject>
            <subject src="/subjects/3if/first_sem/IF-3-MP.pdf">Process Modelling</subject>
            <subject src="/subjects/3if/first_sem/IF-3-BDR.pdf">Data Base Management System</subject>
        </module>
        <module name="Human Sciences and Communication">
            <subject src="education/3if/first_sem/IF-3-SHC-1.pdf">Human Sciences and Communication</subject>
            <subject src="education/3if/first_sem/IF-3-PPP.pdf">Personal and Professional Project</subject>
        </module>
        <module name="Foreign Languages">
            <subject src="/subjects/3if/first_sem/HU-L-ANG-S5.pdf">English Semester 5</subject>
            <subject src="/subjects/3if/first_sem/IF-3-FLE.pdf">French Civilization course B2/C1</subject>
        </module>
        <module name="Sports">
            <subject src="/subjects/3if/first_sem/EPS-3-S1.pdf">Volleyball</subject>
        </module>
        </sem1>

        <sem2>
        <module name="Architecture, System and Network">
            <subject src="/subjects/3if/second_sem/IF-3-SYS.pdf">Operating Systems</subject>
            <subject src="/subjects/3if/second_sem/IF-3-RE.pdf">Network basics</subject>
        </module>
        <module name="Software Development">
            <subject src="/subjects/3if/second_sem/IF-3-GL.pdf">Software Engineering and UML Modelling</subject>
        </module>
        <module name="Models and Mathematical Tools">
            <subject src="/subjects/3if/second_sem/IF-3-AAIA.pdf">Algorithms for Artificial Intelligence and Graphs</subject>
            <subject src="/subjects/3if/second_sem/IF-3-PROB.pdf">Probability</subject>
        </module>
        <module name="Information Systems">
            <subject src="/subjects/3if/second_sem/IF-3-DASI.pdf">Application Development for Information Systems</subject>
            <subject src="/subjects/3if/second_sem/IF-3-DW.pdf">Data Management for the Web</subject>
        </module>
        <module name="Human Sciences and Communication">
            <subject src="/subjects/3if/second_sem/IF-3-SHC-2.pdf">Human Sciences and Communication</subject>
            <subject src="/subjects/3if/second_sem/IF-3-RSI.pdf">Engineering ethics</subject>
            <subject src="/subjects/3if/second_sem/IF-3-PPP-2.pdf">Personal and Professional Project</subject>
        </module>
        <module name="Foreign Languages">
            <subject src="/subjects/3if/second_sem/HU-L-ANG-S6.pdf">English Semester 6</subject>
            <subject src="/subjects/3if/second_sem/IF-3-FLE-2.pdf">French Civilization course 2h per week</subject>
        </module>
        <module name="Sports">
            <subject src="/subjects/3if/second_sem/EPS-3-S2.pdf">Football</subject>
        </module>
        <module name="Internship">
            <subject src="/subjects/3if/second_sem/IF-3-STA.pdf">Internship</subject>
        </module>
        </sem2>
        </if3>

        <if4>
        <sem1>
        <module name="Architecture, System and Network">
            <subject src="/subjects/4if/first_sem/IF-4-PR.pdf">Network Programming</subject>
        </module>
        <module name="Software Development">
            <subject src="/subjects/4if/first_sem/IF-4-PLD-AGILE.pdf">AGILE object oriented software design and development</subject>
        </module>
        <module name="Models and Mathematical Tools">
            <subject src="/subjects/4if/first_sem/IF-4-FD.pdf">Data Mining</subject>
            <subject src="/subjects/4if/first_sem/IF-4-ALIA.pdf">Logical Approach to Artificial Intelligence</subject>
            <subject src="/subjects/4if/first_sem/IF-4-WS.pdf">Semantic Web</subject>
            <subject src="/subjects/4if/first_sem/IF-4-ST.pdf">Statistics</subject>
        </module>
        <module name="Information Systems">
            <subject src="/subjects/4if/first_sem/IF-4-BDD.pdf">Bussiness Intelligence</subject>
            <subject src="/subjects/4if/first_sem/IF-4-WASO.pdf">Web Technologies and Service-oriented Architectures for Organizations</subject>
        </module>
        <module name="Long term project">
            <subject src="/subjects/4if/first_sem/IF-4-PLD-MARS.pdf">Methodology for Design and Deployment of Network and Service Architecture</subject>
        </module>
        <module name="Formation General">
            <subject src="/subjects/4if/first_sem/IF-4-GP.pdf">Project Management</subject>
            <subject src="/subjects/4if/first_sem/IF-4-OGP.pdf">Organization and Management of Services and Goods</subject>
            <subject src="/subjects/4if/first_sem/IF-4-SN.pdf">Numerical Society</subject>
            <subject src="/subjects/4if/first_sem/IF-4-PPP.pdf">Personal and Professional Project</subject>
        </module>
        <module name="Foreign Languages">
            <subject src="/subjects/4if/first_sem/HU-L-ANG-S7.pdf">English Semester 7</subject>
            <subject src="/subjects/4if/first_sem/HU-L-ALL-S1.pdf">German A1</subject>
        </module>
        <module name="Sports">
            <subject src="/subjects/4if/first_sem/EPS-4-S1.pdf">Table tennis</subject>
        </module>
        </sem1>

        <sem2>
        <module name="Architecture, System and Network">
            <subject src="/subjects/4if/second_sem/IF-4-SERE.pdf">Security and Network</subject>
        </module>
        <module name="Software Development">
            <subject src="/subjects/4if/second_sem/IF-4-LG.pdf">Grammar and Languages</subject>
            <subject src="/subjects/4if/second_sem/IF-4-AFQL.pdf">Software Quality</subject>
        </module>
        <module name="Models and Mathematical Tools">
            <subject src="/subjects/4if/second_sem/IF-4-AD.pdf">Decision-Making Support</subject>
            <subject src="/subjects/4if/second_sem/IF-4-ML.pdf">Machine Learning</subject>
        </module>
        <module name="Long term project">
            <subject src="/subjects/4if/second_sem/IF-4-PLD-COMP.pdf">Compiler Project</subject>
            <subject src="/subjects/4if/second_sem/IF-4-PLD-SMART.pdf">PLD SMART</subject>
        </module>
        <module name="Long term project SIE">
            <subject src="/subjects/4if/second_sem/IF-4-PLD-SIE.pdf">PLD SIE</subject>
        </module>
        <module name="Formation General">
            <subject src="/subjects/4if/second_sem/IF-4-MDF.pdf">Management, Law and Finance</subject>
            <subject src="/subjects/4if/second_sem/HUMA-PPH.pdf">Individual Work in Humanities</subject>
        </module>
        <module name="Sports">
            <subject src="/subjects/4if/second_sem/EPS-4-S2.pdf">Tennis</subject>
        </module>
        <module name="Internship">
            <subject src="/subjects/4if/second_sem/IF-4-STA.pdf">Internship</subject>
        </module>
        </sem2>
        </if4>
    </education>

    <projects>
        <time time="First year">
            <project src="https://github.com/minhngo248/Fractal">Drawing fractal using turtle Python</project>
        </time>
        <time time="Second year">
            <project src="https://github.com/minhngo248/jeu2048">Game 2048</project>
            <project src="https://github.com/minhngo248/Web_Asso_Sport">Web Design for Sportive Club</project>
        </time>
        <time time="Third year">
            <project src="https://github.com/minhngo248/Trajet65884">Find the itenery</project>
            <project src="https://github.com/minhngo248/Apache-logs-analyse">Automatic log generating</project>
            <project src="https://github.com/minhngo248/Projet_reactif">Back-end project</project>
            <project src="https://github.com/minhngo248/projetpredict">Front-end project</project>
            <project src="https://github.com/minhngo248/Projet_airwatcher">App for managing the air-quality machine</project>
        </time>
        <time time="Internship third year at the Astrophysical Research Centre of Lyon">
            <project src="https://git-cral.univ-lyon1.fr/minh.ngo/hlsf">Estimation of the Line Spread Function from data of the astrophysical instrument H.A.R.M.O.N.I of European Southern 
        Observatory</project>
        </time>
        <time time="Fourth year">
            <project src="https://github.com/minhduc-phung/4IF-AGILE">Long term project AGILE</project>
            <project src="https://github.com/minhngo248/tp_pr_rendu">Real-time chat</project>
